<!-- Generated by LoopForge onboarding v2; seed -->
# {{PROJECT_NAME}} Python 架构约束

## 边界

脚本项目也必须分离入口、业务逻辑和副作用：

```text
CLI/entrypoint → application function → domain/transform → adapters/files/network/process
```

- 入口只解析参数、装配依赖、调用应用函数并映射退出码。
- 核心转换接受普通值并返回明确结果，不在 import 时读文件、联网或启动子进程。
- 文件、HTTP、数据库和子进程集中在 adapter 边界，便于测试和替换。
- 配置加载一次并验证；不要在多个模块散落环境变量读取。

## 模块设计

- 使用有职责的模块名，避免不断增长的 `utils.py`。
- 公共类型和协议只为真实消费者建立，不为“以后可能用”抽象。
- 导入必须无副作用；可执行入口放在 `main()` 和 `if __name__ == "__main__"` 下。
- 同步/异步边界保持一致，不在库函数内部任意创建事件循环。

## 错误与资源

- 领域错误与外部系统错误分开，CLI 统一生成稳定退出码和简洁消息。
- 文件句柄、临时目录、锁、session 和子进程必须有确定清理路径。
- 不捕获宽泛异常后静默成功；重试必须有次数、超时和幂等依据。

业务事实与数据格式写入模块 `docs/*`，本文不复制具体脚本协议。
