<!-- Generated by LoopForge onboarding v2; seed -->
# {{PROJECT_NAME}} Python 构建与运行

## 标准入口

```text
scripts/setup-tools.sh
scripts/format.sh
scripts/format-check.sh
scripts/lint.sh
scripts/test.sh
scripts/build.sh
```

Python 脚本项目的通用 build 是 `compileall` 语法/字节码检查；如果项目是可分发 package，应由项目另行配置 `python -m build` 和制品验证。

## 环境

- Python 版本和依赖以 `pyproject.toml`、lockfile 或项目文档为准。
- `.venv` 是默认本地隔离目录；`scripts/python-env.sh` 优先使用其中解释器。
- `setup-tools.sh` 只安装质量工具，不替代项目依赖安装。
- Ruff 同时承担格式化和 lint，配置写入 `pyproject.toml`/`ruff.toml`，不要再并行运行会冲突的 formatter。

## 运行边界

- 项目入口必须支持 `--help`，参数错误返回非零退出码。
- dry-run、输出目录、覆盖策略和幂等性按 `SCRIPT_ENGINEERING.md` 定义。
- 示例配置不含真实 token、账号、生产地址或个人绝对路径。
- 通用脚本不得自动上传、发布、发送消息或连接生产服务。

修改 Python 版本、依赖管理、入口或质量工具时同步本文、脚本和 CI。
