<!-- Generated by LoopForge onboarding v2; seed -->
# {{PROJECT_NAME}} Python 测试约束

## 最低门禁

源码变更至少运行 format-check、lint、test 和 build。`test.sh` 在环境提供 pytest 时使用 pytest，否则使用标准库 unittest discovery。

## 测试分层

- Unit：纯转换、解析、校验和状态逻辑。
- CLI：真实解析器、stdout/stderr、退出码和文件副作用。
- Adapter：临时目录、本地 HTTP fake 或隔离数据库，禁止真实外部服务。
- Smoke：每个可执行入口至少覆盖 `--help` 和一个无外部服务场景。

## 编写规则

- 测试名说明被捕获的错误；期望值独立构造，不复用被测 helper。
- 优先使用 `tempfile`、明确 fixture 和依赖注入；不要依赖个人目录和执行顺序。
- mock 前先确认真实方法的全部副作用，只截断慢或外部一层。
- 覆盖空输入、非法编码、损坏 JSON、路径越界、重复执行、超时和中断清理。
- 时间和随机值必须可控制；子进程断言真实退出码与输出。

失败后修复并重跑。外部条件缺失时记录未验证范围，不把 skip 说成通过。
