#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed
set -euo pipefail

PROJECT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$PROJECT_ROOT_DIR/scripts/go-env.sh"
cd "$PROJECT_ROOT_DIR"
while IFS= read -r package; do
  if [ -n "$package" ]; then
    go build -o /dev/null "$package"
  fi
done < <(go list -f '{{if .GoFiles}}{{.ImportPath}}{{end}}' ./...)
