#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed
set -euo pipefail

PROJECT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$PROJECT_ROOT_DIR/scripts/go-env.sh"
source "$PROJECT_ROOT_DIR/scripts/tool-env.sh"
cd "$PROJECT_ROOT_DIR"
GOIMPORTS_BIN="$(require_project_tool goimports "$GOIMPORTS_VERSION")"

go_file_list="$(mktemp)"
gofmt_result="$(mktemp)"
goimports_result="$(mktemp)"
trap 'rm -f "$go_file_list" "$gofmt_result" "$goimports_result"' EXIT
find . -name '*.go' -not -path './.git/*' -print0 > "$go_file_list"
if [ ! -s "$go_file_list" ]; then
  echo "没有需要检查的 Go 文件。"
  exit 0
fi
xargs -0 gofmt -l < "$go_file_list" > "$gofmt_result"
xargs -0 "$GOIMPORTS_BIN" -l < "$go_file_list" > "$goimports_result"
if [ -s "$gofmt_result" ] || [ -s "$goimports_result" ]; then
  echo "以下 Go 文件需要格式化："
  sort -u "$gofmt_result" "$goimports_result"
  echo "请运行 scripts/format.sh。"
  exit 1
fi
echo "Go 格式检查通过。"
