#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed
set -euo pipefail

PROJECT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$PROJECT_ROOT_DIR/scripts/go-env.sh"
source "$PROJECT_ROOT_DIR/scripts/tool-env.sh"
cd "$PROJECT_ROOT_DIR"
GOIMPORTS_BIN="$(require_project_tool goimports "$GOIMPORTS_VERSION")"

go_file_list="$(mktemp)"
trap 'rm -f "$go_file_list"' EXIT
find . -name '*.go' -not -path './.git/*' -print0 > "$go_file_list"
if [ ! -s "$go_file_list" ]; then exit 0; fi
xargs -0 gofmt -w < "$go_file_list"
xargs -0 "$GOIMPORTS_BIN" -w < "$go_file_list"
