#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed

if [ -n "${GOROOT:-}" ] && [ ! -d "${GOROOT}/src/fmt" ]; then
  echo "忽略无效 GOROOT：${GOROOT}" >&2
  unset GOROOT
fi

export GOPROXY="${GOPROXY:-https://goproxy.cn|https://proxy.golang.org|direct}"
export GOSUMDB="${GOSUMDB:-sum.golang.org}"
