#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed
set -euo pipefail

PROJECT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$PROJECT_ROOT_DIR/scripts/go-env.sh"
source "$PROJECT_ROOT_DIR/scripts/tool-env.sh"
cd "$PROJECT_ROOT_DIR"
GOLANGCI_LINT_BIN="$(require_project_tool golangci-lint "$GOLANGCI_LINT_VERSION")"
"$GOLANGCI_LINT_BIN" run ./...
