#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed
set -euo pipefail

PROJECT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$PROJECT_ROOT_DIR/scripts/go-env.sh"
cd "$PROJECT_ROOT_DIR"

go mod download all
"$PROJECT_ROOT_DIR/scripts/setup-tools.sh"
