#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed
set -euo pipefail

PROJECT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$PROJECT_ROOT_DIR/scripts/go-env.sh"
source "$PROJECT_ROOT_DIR/scripts/tool-env.sh"
cd "$PROJECT_ROOT_DIR"
mkdir -p "$PROJECT_TOOLS_BIN"

echo "安装 goimports (${GOIMPORTS_VERSION}) 到 ${PROJECT_TOOLS_BIN}"
GOBIN="$PROJECT_TOOLS_BIN" go install "golang.org/x/tools/cmd/goimports@${GOIMPORTS_VERSION}"
printf '%s\n' "$GOIMPORTS_VERSION" > "$PROJECT_TOOLS_DIR/goimports.version"
echo "安装 golangci-lint (${GOLANGCI_LINT_VERSION}) 到 ${PROJECT_TOOLS_BIN}"
GOBIN="$PROJECT_TOOLS_BIN" go install "github.com/golangci/golangci-lint/cmd/golangci-lint@${GOLANGCI_LINT_VERSION}"
printf '%s\n' "$GOLANGCI_LINT_VERSION" > "$PROJECT_TOOLS_DIR/golangci-lint.version"
echo "项目本地 Go 工具准备完成。"
