#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed
set -euo pipefail

PROJECT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$PROJECT_ROOT_DIR/scripts/go-env.sh"
cd "$PROJECT_ROOT_DIR"

MODE="${1:-unit}"
if [ "$#" -gt 0 ]; then shift; fi

run_unit() {
  local package_list package
  local -a packages=()
  package_list="$(go list ./...)"
  while IFS= read -r package; do
    case "$package" in
      */test/integration|*/test/integration/*) continue ;;
    esac
    [ -n "$package" ] && packages+=("$package")
  done <<< "$package_list"
  if [ "${#packages[@]}" -eq 0 ]; then
    echo "没有可测试的 Go package。"
    return 0
  fi
  go test "${packages[@]}" "$@"
}

run_integration() {
  if [ ! -d "test/integration" ]; then
    echo "未发现 test/integration，跳过集成测试。"
    return 0
  fi
  go test -tags=integration ./test/integration/... "$@"
}

case "$MODE" in
  unit) run_unit "$@" ;;
  integration) run_integration "$@" ;;
  all)
    run_unit "$@"
    run_integration "$@"
    ;;
  *)
    echo "用法：scripts/test.sh [unit|integration|all] [go test 参数]" >&2
    exit 2
    ;;
esac
