#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed

if [ -z "${PROJECT_ROOT_DIR:-}" ]; then
  PROJECT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi

PROJECT_TOOLS_DIR="${PROJECT_TOOLS_DIR:-$PROJECT_ROOT_DIR/.tools}"
PROJECT_TOOLS_BIN="${PROJECT_TOOLS_BIN:-$PROJECT_TOOLS_DIR/bin}"
GOIMPORTS_VERSION="${GOIMPORTS_VERSION:-v0.30.0}"
GOLANGCI_LINT_VERSION="${GOLANGCI_LINT_VERSION:-v1.64.8}"

require_project_tool() {
  local tool_name="$1"
  local expected_version="$2"
  local tool_path="$PROJECT_TOOLS_BIN/$tool_name"
  local version_file="$PROJECT_TOOLS_DIR/${tool_name}.version"
  if [ ! -x "$tool_path" ] || [ ! -f "$version_file" ] || [ "$(<"$version_file")" != "$expected_version" ]; then
    echo "缺少 $tool_name ($expected_version)：先运行 scripts/setup-tools.sh。" >&2
    return 1
  fi
  printf '%s\n' "$tool_path"
}
