#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed
set -euo pipefail
PROJECT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$PROJECT_ROOT_DIR/scripts/flutter-env.sh"
cd "$PROJECT_ROOT_DIR"
BUILD_TARGET="${1:-{{FLUTTER_BUILD_TARGET}}}"
if [ -z "$BUILD_TARGET" ]; then
  echo '无法唯一确定 Flutter 构建目标；请传入 scripts/build.sh <target>。' >&2
  exit 2
fi
shift || true
flutter build "$BUILD_TARGET" "$@"
