#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed

if ! command -v flutter >/dev/null 2>&1; then
  echo '未找到 flutter，请先安装项目要求的 Flutter SDK。' >&2
  return 1 2>/dev/null || exit 1
fi
if ! command -v dart >/dev/null 2>&1; then
  echo '未找到 dart，请检查 Flutter SDK 环境。' >&2
  return 1 2>/dev/null || exit 1
fi
