#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed
set -euo pipefail
PROJECT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$PROJECT_ROOT_DIR/scripts/flutter-env.sh"
cd "$PROJECT_ROOT_DIR"
flutter test "$@"
