<!-- Generated by LoopForge onboarding v2; seed -->
# {{PROJECT_NAME}} React 架构约束

## 文档边界

本文固定 React 18 + Umi Max 4 + Ant Design 5/ProComponents 2 的目录职责、依赖方向和页面装配边界；具体业务行为与接口写入 `docs/<module>/requirements.md|design.md|specs.md`。

## 目录与职责

```text
config/routes.ts 或 .umirc.ts  # Umi 路由、插件和构建配置
src/app.tsx                    # 运行时初始化、请求拦截和全局布局
src/access.ts                  # 前端展示权限
src/pages/                     # 路由页面入口
src/features/                  # 一个用户能力的状态与交互编排
src/components/                # 可复用 Ant Design/ProComponents 展示组件
src/hooks/                     # 可复用状态与副作用
src/services/                  # API client、DTO 校验/转换和错误归一
src/models/                    # Umi 全局或跨页面状态；只在确有共享状态时使用
```

目录只在承担真实职责时创建，不制造空层。

## 依赖方向

```text
route/page → feature → component/hook → service → external API
```

- 页面负责路由参数、页面级加载和 feature 组合，不承载可复用业务协议。
- feature 组织一个用户能力的状态与交互，不直接拼接请求 URL。
- component 通过明确 props 表达 UI；优先组合 Ant Design/ProComponents 与项目 token。
- hook 封装可复用状态或副作用，明确依赖、取消和清理。
- service 是 API、DTO、View Model 和错误归一的唯一边界，具体数据规则见 `DATA_CONTRACT.md`。
- 内层模块不得反向导入 page；组件层不得导入 Node-only 模块或读取 secrets。

## 状态、路由与权限

- 远端状态、URL 状态、表单状态和局部视觉状态分开建模，不复制服务端权威业务状态。
- 路由、菜单、面包屑和访问控制来自同一稳定配置或明确映射。
- 前端权限只控制展示与交互，后端仍负责授权。
- 404、403、空态、加载和失败必须可区分，不把异常转成“正常空列表”。
- 项目选择额外状态库、样式方案或 Umi 插件时，在本文登记真实边界；不得更换固定基础栈而不更新模板合同。
