<!-- Generated by LoopForge onboarding v2; seed -->
# {{PROJECT_NAME}} React 构建与运行

## 包管理器

onboarding 检测到的默认包管理器为 `{{PACKAGE_MANAGER}}`。最终以 `packageManager` 字段和锁文件为准；一个仓库只维护一种权威锁文件。

固定运行栈为 React 18、Umi Max 4、Ant Design 5/ProComponents 2。onboarding 只写依赖声明，不在 preview/apply 中联网。

## 标准入口

```text
scripts/setup.sh [--refresh-lock] # 默认按锁文件安装；显式参数刷新依赖锁
scripts/format.sh        # package script: format
scripts/format-check.sh  # package script: format:check
scripts/lint.sh          # package script: lint
scripts/test.sh [unit|all]                # 普通测试入口
scripts/build.sh         # package script: build
```

包装脚本只委托 `package.json`，不复制框架长命令。缺少对应 package script 时必须先在项目中明确配置，doctor 会阻止自动执行。

依赖声明因 onboarding 变化后先运行 `scripts/setup.sh --refresh-lock`，提交 `package.json` 与权威 lockfile；日常和 CI 使用无参数 `scripts/setup.sh` 的 frozen/CI 安装。

## 运行边界

- Umi 开发入口、端口、代理和环境变量以 `package.json` 与项目配置文件为准。
- `.env.example` 只能包含变量名和安全示例，不包含真实 token、Cookie、账号或生产地址。
- 构建产物和框架生成目录不作为源码编辑目标。
- 安装、构建和测试不得隐式发布、部署或写远端环境。

## 变更同步

修改 package script、锁文件、Node 版本、代理、构建目录或质量工具时，同时更新本文、包装脚本和 CI。
