<!-- Generated by LoopForge onboarding v2; seed -->
# {{PROJECT_NAME}} React 数据契约

## 文档边界

本文定义 API 响应进入前端后的通用处理；具体字段、状态、权限点和业务计算写入模块 specs。

## 数据流

```text
API response → transport DTO → validation/normalization → View Model → component
```

- 页面不直接拼 URL 或猜响应 envelope；请求集中在 service/client 层。
- Umi 页面和 model 只消费 service 返回的稳定结果，不直接保存 transport response 或 Ant Design 表格临时结构作为业务事实。
- DTO 与 View Model 允许不同，但转换必须显式、可测试。
- 后端字段缺失、null、空数组、404、403 和网络失败分别建模。
- mock 只能表达已确认协议或明确占位，不得成为真实字段来源。

## 展示规则

- 金额必须携带币种和明确单位；精确金额不使用浮点计算。
- 时间必须明确时区、解析格式和展示格式。
- 分页、排序和筛选只提交协议允许字段，不伪造 total。
- 枚举未知值使用安全 fallback 并保留诊断，不静默映射为正常状态。

## 认证与敏感信息

- 登录态、CSRF、Bearer token 等遵守项目真实协议，不从模板选择方案。
- secrets、token、Cookie 和个人数据不得进入日志、错误文案、fixture 或持久化浏览器存储，除非协议明确要求且经过安全审查。
- 前端展示权限不能替代服务端授权；无权限时敏感字段默认隐藏或脱敏。

## 变更检查

新增字段前确认来源、消费者、空值、单位、权限、敏感性和向后兼容，并同步模块 specs 与相关测试。
