<!-- Generated by LoopForge onboarding v2; seed -->
# {{PROJECT_NAME}} React 测试约束

## 最低门禁

源码改动至少运行标准 format/lint/unit/build。涉及 selector、布局或网络细节时再运行项目自有 UI flow。

## 测试分层

- Unit：纯函数、格式化、校验和 reducer。
- Component：真实组件的可见行为、键盘操作、加载/空/错状态。
- Integration：页面、路由、service 与状态层协作，外部 API 在网络边界替换。
- E2E：关键用户流、权限和跨页状态，使用隔离账号/fixture。

## UI Flow

UI flow 覆盖 selector、网络协议、像素布局与深层技术边界，可复用 driver、fixture 和页面动作。页面装配和断言失败必须非零退出。

## 编写规则

- 按用户可观察行为断言，优先 role、label 和可见文案，不依赖私有 class 或实现层级。
- 不断言 mock 组件存在；mock 只截断真实外部边界。
- 覆盖 loading、empty、error、unauthorized、forbidden 和 retry，不把所有失败映射为空态。
- 时间、金额、时区、分页和敏感字段按真实协议构造 fixture。
- 测试必须清理 timer、listener、server 和临时浏览器资源。

## 视觉与可访问性

布局或交互变更需要检查目标 viewport、键盘导航、focus、语义标签和对比度。人工探索可以补充观察，但不能替代可重复门禁。

## 失败处理

不得声称运行了项目未配置的测试。外部条件阻塞时，记录失败命令、未验证范围和恢复条件。
