<!-- Generated by LoopForge onboarding v2; seed -->
# {{PROJECT_NAME}} 子仓登记规范

## 权威集合

项目成员只来自 onboarding 时显式选择并写入项目 profile 的 `project_group.children[]`。目录自动探测仅提供候选，不能静默登记。

每个 child 至少包含：

- `key`：Target 使用的稳定标识。
- `path`：可解析的仓库路径。
- `repo`：人类可读仓库名称。

## 职责记录

在本文件追加项目实际子仓表，至少记录 key、职责、主要技术栈、协议所有者和默认质量入口。业务字段、内部包结构和任务状态仍留在子仓自身文档。

## 变更规则

- 新增子仓需要人工确认并通过 doctor。
- 移除子仓前检查未完成 Target 和长期协议消费者。
- path 变化只更新项目配置，不改写历史任务结果。
- 子仓不可访问、key 重复或 Target 引用未知 key 时，在启动 Worker 前阻塞。
