<!-- Generated by LoopForge onboarding v2; seed -->
# {{PROJECT_NAME}} Java 架构约束

## 边界

本文定义模块、包、应用层和适配器依赖；业务流程和协议写入模块 `docs/*`。

```text
bootstrap/controller → application → domain → ports ← infrastructure
```

- controller 处理协议转换、认证上下文和输入校验，不承载领域流程。
- application 编排事务、授权和用例。
- domain 保存不依赖 Spring/JPA/HTTP 的核心规则。
- ports 由消费者定义；infrastructure 实现数据库、消息和第三方系统。
- bootstrap/config 负责装配，不成为全局 service locator。

## 包与模块

- Maven/Gradle 多模块依赖必须单向，禁止循环依赖。
- package-private 优先表达模块内部边界；公共 API 保持最小。
- DTO、entity 和 domain model 不混用；转换集中在边界。
- checked/unchecked exception 按项目现有策略统一，协议层集中映射稳定错误。

## 并发与事务

- 事务边界位于应用用例，不跨远程调用长期持有数据库事务。
- 明确线程池、异步上下文、取消和 MDC/trace 传播。
- 不以 synchronized 或全局锁掩盖数据库并发与幂等问题。

项目使用 Spring、Jakarta、Micronaut 或 Quarkus 时，以实际构建文件和代码为准，模板不替换框架选择。
