<!-- Generated by LoopForge onboarding v2; seed -->
# {{PROJECT_NAME}} Java 构建与运行

## 构建工具

探测到的构建工具为 `{{JAVA_BUILD_TOOL}}`。脚本优先使用项目提交的 Maven Wrapper `./mvnw` 或 Gradle Wrapper `./gradlew`；缺少 Wrapper 时才回退系统命令并由 doctor 提示。

## 标准入口

```text
scripts/format.sh
scripts/format-check.sh
scripts/lint.sh
scripts/test.sh
scripts/build.sh
```

format/lint 不存在跨所有 Java 项目的单一命令。`scripts/build-tool.sh` 只调用构建文件已经声明的 Spotless/Checkstyle 等 task 或 goal；未配置时明确失败，不静默跳过。

## 环境

- JDK 版本以 Maven/Gradle toolchain、compiler 配置或项目文档为准。
- 不混用 Maven 和 Gradle 依赖缓存或生命周期。
- 依赖版本、插件版本和 BOM 修改必须审查 lock/catalog/build 文件差异。
- 项目运行入口、profile、端口和外部服务写入项目专用文档与脚本。

## 安全边界

通用脚本不得发布 artifact、推送镜像、执行生产迁移或读取真实 secrets。构建产物不作为源码编辑目标。
