<!-- Generated by LoopForge onboarding v2; seed -->
# {{PROJECT_NAME}} Java 数据工程约束

## 事实来源

DDL/迁移定义数据库事实，模块 specs 定义业务语义，entity/repository 是实现映射。不得根据 JPA annotation 单方面发明或修改生产 schema。

## 持久化

- entity 与 domain model 分离，避免 lazy proxy、持久化状态和框架 annotation 泄漏到领域层。
- repository 方法表达用例需要，明确分页、排序、锁和 not-found 语义。
- N+1、批量写入、事务隔离和连接生命周期需要可验证证据。
- 事务由 application 层控制；远程调用与长计算不应占用事务。

## 迁移与兼容

- schema 变化说明上线顺序、旧应用兼容、数据回填和回滚/前向修复。
- 修改非空、唯一、外键、索引、精度或 enum 时先评估存量数据。
- 金额使用精确类型并明确 scale/currency；时间明确 instant、zone 和数据库类型。
- serializer、event 和 API DTO 的兼容策略独立于数据库 entity。

## 测试与安全

迁移和 repository 测试使用隔离数据库；不得连接生产或共享实例。日志与 fixture 不含真实个人数据、token 或连接凭证。
