<!-- Generated by LoopForge onboarding v2; seed -->
# {{PROJECT_NAME}} Java 测试约束

## 最低门禁

源码改动至少运行 format-check、lint、test 和 build。未配置格式化/静态检查插件时，先把质量能力纳入构建文件，不能把脚本改成无条件成功。

## 测试分层

- Unit：domain、application 和纯转换，使用真实值对象与最小 fake。
- Slice/Component：Web、serialization、repository 等单一框架切片。
- Integration：数据库、消息和外部 adapter，使用隔离容器或可重复 fixture。
- E2E：关键协议流和部署组合，由项目专用脚本负责。

## 编写规则

- 测试名说明行为和条件，断言稳定结果而非调用次数堆砌。
- mock 只截断慢或外部边界，不 mock 被测对象的数据转换和事务副作用。
- 覆盖 null/empty、非法状态、权限、超时、并发更新和重复请求。
- 数据库测试必须隔离 schema/transaction，并验证 constraint 与 rollback。
- 测试不得依赖顺序、系统时区、个人目录或共享服务。

门禁失败必须修复重跑；环境阻塞时记录命令、范围和恢复条件。
