#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed
set -euo pipefail
PROJECT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$PROJECT_ROOT_DIR/scripts/python-env.sh"
cd "$PROJECT_ROOT_DIR"
"$PROJECT_PYTHON_BIN" -m ruff check --select I .
"$PROJECT_PYTHON_BIN" -m ruff format --check .
