#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed

if [ -z "${PROJECT_ROOT_DIR:-}" ]; then
  PROJECT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi
if [ -x "$PROJECT_ROOT_DIR/.venv/bin/python" ]; then
  PROJECT_PYTHON_BIN="$PROJECT_ROOT_DIR/.venv/bin/python"
else
  PROJECT_PYTHON_BIN="${PROJECT_PYTHON_BIN:-python3}"
fi
if ! command -v "$PROJECT_PYTHON_BIN" >/dev/null 2>&1; then
  echo "未找到 Python：$PROJECT_PYTHON_BIN" >&2
  return 1 2>/dev/null || exit 1
fi
