#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed
set -euo pipefail
PROJECT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$PROJECT_ROOT_DIR/scripts/python-env.sh"
RUFF_VERSION="${RUFF_VERSION:-0.12.9}"
"$PROJECT_PYTHON_BIN" -m pip install "ruff==$RUFF_VERSION"
