#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed
set -euo pipefail
PROJECT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$PROJECT_ROOT_DIR/scripts/python-env.sh"
cd "$PROJECT_ROOT_DIR"
if "$PROJECT_PYTHON_BIN" -c 'import pytest' >/dev/null 2>&1; then
  "$PROJECT_PYTHON_BIN" -m pytest "$@"
else
  "$PROJECT_PYTHON_BIN" -m unittest discover "$@"
fi
