#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed

PROJECT_PACKAGE_MANAGER="{{PACKAGE_MANAGER}}"

run_package_script() {
  local script_name="$1"
  shift
  case "$PROJECT_PACKAGE_MANAGER" in
    npm) npm run "$script_name" -- "$@" ;;
    pnpm) pnpm run "$script_name" "$@" ;;
    yarn) yarn run "$script_name" "$@" ;;
    *) echo "不支持的包管理器：$PROJECT_PACKAGE_MANAGER" >&2; return 2 ;;
  esac
}
