#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed
set -euo pipefail

PROJECT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$PROJECT_ROOT_DIR/scripts/package-manager.sh"
cd "$PROJECT_ROOT_DIR"
REFRESH_LOCK="${1:-}"
if [ "$REFRESH_LOCK" = "--refresh-lock" ]; then
  case "$PROJECT_PACKAGE_MANAGER" in
    npm) npm install ;;
    pnpm) pnpm install --no-frozen-lockfile ;;
    yarn) yarn install ;;
    *) echo "不支持的包管理器：$PROJECT_PACKAGE_MANAGER" >&2; exit 2 ;;
  esac
  exit 0
fi
if [ -n "$REFRESH_LOCK" ]; then
  echo "用法：scripts/setup.sh [--refresh-lock]" >&2
  exit 2
fi
case "$PROJECT_PACKAGE_MANAGER" in
  npm) if [ -f package-lock.json ]; then npm ci; else npm install; fi ;;
  pnpm) if [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile; else pnpm install; fi ;;
  yarn) if [ -f yarn.lock ]; then yarn install --frozen-lockfile; else yarn install; fi ;;
  *) echo "不支持的包管理器：$PROJECT_PACKAGE_MANAGER" >&2; exit 2 ;;
esac
