#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed
set -euo pipefail
PROJECT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$PROJECT_ROOT_DIR/scripts/package-manager.sh"
cd "$PROJECT_ROOT_DIR"

MODE="${1:-unit}"
if [ "$#" -gt 0 ]; then shift; fi

case "$MODE" in
  unit) run_package_script test "$@" ;;
  all) run_package_script test "$@" ;;
  *)
    echo "用法：scripts/test.sh [unit|all] [测试参数]" >&2
    exit 2
    ;;
esac
