"""新项目接入的预检、脚手架计划与幂等应用。"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict

from .config import ProjectProfile, read_projects_config, write_projects_config
from .dev_tasks import ensure_dev_task_file, read_payload, uses_v2_storage, validate_payload
from .task_git import read_sync_blocker
from .project_paths import ProjectPathError, resolve_project_path


TEMPLATE_ROOT = Path(__file__).resolve().parent.parent / "templates" / "onboarding"
LEGACY_AGENTS_START = "<!-- LOOPFORGE:AGENT-DOCS:START -->"
LEGACY_AGENTS_END = "<!-- LOOPFORGE:AGENT-DOCS:END -->"
GENERATED_MARKER = "Generated by LoopForge onboarding v2; managed"
GENERATED_MARKERS = (GENERATED_MARKER, "Generated by LoopForge onboarding v1; managed")
FLUTTER_BUILD_TARGETS = {"apk", "appbundle", "aar", "web", "ios", "ipa", "macos", "linux", "windows"}
PLANNING_ADAPTERS = {"builtin", "openspec"}
DEFAULT_PLANNING_ADAPTER = "builtin"


def onboarding_preview(
    root_dir: Path | str,
    project_type: str,
    *,
    project_id: str = "",
    name: str = "",
    planning_adapter: str = "",
    owner: str = "",
    build_target: str = "",
    project_group_children: list[Dict[str, Any]] | None = None,
) -> Dict[str, Any]:
    root_value = str(root_dir or "").strip()
    root = Path(root_value).expanduser() if root_value else Path("__loopforge_missing_project_root__")
    clean_type = str(project_type or "").strip()
    manifest = _load_manifest()
    profiles = manifest.get("profiles") if isinstance(manifest.get("profiles"), dict) else {}
    profile = profiles.get(clean_type)
    blockers: list[Dict[str, str]] = []
    if not root_value or not root.exists() or not root.is_dir():
        blockers.append(_blocker("project_root_missing", f"项目目录不存在：{root}"))
    if not isinstance(profile, dict):
        blockers.append(_blocker("project_type_unknown", f"不支持的项目类型：{clean_type}"))
        clean_adapter = _resolve_planning_adapter(root, planning_adapter, blockers)
        clean_owner = str(owner or "").strip()
        if not clean_owner:
            blockers.append(_blocker("onboarding_owner_required", "项目接入必须提供 owner。"))
        return _preview_result(
            root,
            clean_type,
            {},
            [],
            blockers,
            {},
            clean_adapter,
            owner=clean_owner,
            workflow_initialization=_workflow_initialization(root, clean_adapter, clean_owner),
        )

    evidence = _profile_evidence(root, clean_type)
    if not evidence["matched"]:
        blockers.append(_blocker("profile_evidence_missing", str(evidence["summary"])))
    existing_dev_task = root / "data" / "dev-task.json"
    if existing_dev_task.exists():
        try:
            validate_payload(read_payload(existing_dev_task))
        except Exception as exc:
            blockers.append(_blocker("dev_task_invalid", f"data/dev-task.json 无效：{exc}", "data/dev-task.json"))

    clean_id = _slug(project_id or root.name)
    project_name = str(name or root.name or clean_id).strip()
    selected_build_target = str(build_target or "").strip().lower()
    detected_build_target = _detect_flutter_build_target(root)
    if clean_type == "flutter-app":
        if selected_build_target and selected_build_target not in FLUTTER_BUILD_TARGETS:
            blockers.append(
                _blocker(
                    "flutter_build_target_invalid",
                    "不支持的 Flutter build target："
                    + selected_build_target
                    + "；可选值："
                    + ", ".join(sorted(FLUTTER_BUILD_TARGETS)),
                )
            )
        elif not selected_build_target and not detected_build_target:
            blockers.append(
                _blocker(
                    "flutter_build_target_required",
                    "未能唯一确定 Flutter 构建平台；请显式选择 build target。",
                )
            )
    effective_build_target = selected_build_target or detected_build_target
    variables = {
        "PROJECT_ID": clean_id,
        "PROJECT_NAME": project_name,
        "PROJECT_TYPE": clean_type,
        "PROFILE_LABEL": str(profile.get("label") or clean_type),
        "FIFTH_DOC": str(profile.get("fifth_doc") or "PROJECT_GUIDE.md"),
        "PACKAGE_MANAGER": _detect_package_manager(root),
        "FLUTTER_BUILD_TARGET": effective_build_target,
        "JAVA_BUILD_TOOL": _detect_java_build_tool(root),
    }
    desired_files = _desired_files(profile, variables)
    file_entries = {str(entry["path"]): entry for entry in _profile_file_entries(profile)}
    required_agent_docs = _required_agent_docs(variables["FIFTH_DOC"])
    files: list[Dict[str, Any]] = []
    for rel, generated in desired_files.items():
        file_entry = file_entries[rel]
        try:
            path = resolve_project_path(root, rel)
        except ProjectPathError as exc:
            blockers.append(_blocker("onboarding_path_outside_project", str(exc), rel))
            continue
        current = _read_optional(path)
        desired = _reconcile_agents(current, generated, required_agent_docs) if rel == "AGENTS.md" else generated
        if current is None:
            action = "create"
        elif current == desired:
            action = "unchanged"
        elif rel == "AGENTS.md":
            action = "update"
        elif str(file_entry.get("management") or "seed") == "contract" and _is_generated(current):
            action = "update"
        elif str(file_entry.get("management") or "seed") == "managed" and GENERATED_MARKER in current:
            action = "update"
        else:
            action = "skip"
        if (
            current is not None
            and bool(file_entry.get("executable"))
            and not bool(path.stat().st_mode & 0o111)
            and action in {"unchanged", "skip"}
        ):
            action = "chmod"
            desired = current
        files.append(
            {
                "path": rel,
                "action": action,
                "current_hash": _digest(current or ""),
                "desired_hash": _digest(desired),
                "content": desired,
                "executable": bool(file_entry.get("executable")),
                "management": str(file_entry.get("management") or "seed"),
            }
        )
    files.append(_tracked_project_config_entry(root, clean_type))

    dependency_entry = _dependency_file_entry(root, profile, blockers)
    if dependency_entry is not None:
        files.append(dependency_entry)

    clean_adapter = _resolve_planning_adapter(root, planning_adapter, blockers)
    clean_owner = str(owner or "").strip()
    if not clean_owner:
        blockers.append(_blocker("onboarding_owner_required", "项目接入必须提供 owner。"))
    workflow_initialization = _workflow_initialization(root, clean_adapter, clean_owner)
    group_children: list[Dict[str, str]] = []
    if clean_type == "project-group":
        group_children = (
            _detect_project_group_children(root)
            if project_group_children is None
            else _normalize_project_group_children(root, project_group_children, blockers)
        )
    profile_draft = _profile_draft(root, clean_id, project_name, clean_type, clean_adapter, group_children)
    preview = _preview_result(
        root,
        clean_type,
        profile,
        files,
        blockers,
        profile_draft,
        clean_adapter,
        evidence=evidence,
        build_target=effective_build_target,
        owner=clean_owner,
        workflow_initialization=workflow_initialization,
    )
    preview["warnings"].extend(
        _quality_warnings(root, clean_type, profile, build_target=effective_build_target)
    )
    preview["warnings"].extend(_dependency_warnings(files, clean_type))
    return preview


def onboarding_apply(
    config_path: Path | None,
    root_dir: Path | str,
    project_type: str,
    *,
    project_id: str = "",
    name: str = "",
    planning_adapter: str = "",
    owner: str = "",
    build_target: str = "",
    project_group_children: list[Dict[str, Any]] | None = None,
    plan_hash: str,
) -> Dict[str, Any]:
    preview = onboarding_preview(
        root_dir,
        project_type,
        project_id=project_id,
        name=name,
        planning_adapter=planning_adapter,
        owner=owner,
        build_target=build_target,
        project_group_children=project_group_children,
    )
    if preview["status"] != "completed":
        return preview
    if not plan_hash or plan_hash != preview["plan_hash"]:
        return {
            "status": "blocked",
            "summary": "onboarding 计划已变化，请重新预检后再确认生成。",
            "code": "onboarding_plan_changed",
            "expected_plan_hash": preview["plan_hash"],
        }
    try:
        _validate_registration(config_path, dict(preview["profile"]))
    except ValueError as exc:
        return {
            "status": "blocked",
            "summary": str(exc),
            "code": "project_registration_conflict",
            "written": [],
            "skipped": [],
        }

    root = Path(root_dir).expanduser().resolve()
    written: list[str] = []
    skipped: list[str] = []
    for entry in preview["files"]:
        rel = str(entry["path"])
        if entry["action"] in {"unchanged", "skip"}:
            skipped.append(rel)
            continue
        path = resolve_project_path(root, rel)
        path.parent.mkdir(parents=True, exist_ok=True)
        if entry["action"] != "chmod":
            path.write_text(str(entry["content"]), encoding="utf-8")
        if entry.get("executable"):
            path.chmod(path.stat().st_mode | 0o755)
        written.append(rel)

    ensure_dev_task_file(root, str(preview["profile"]["name"]))
    try:
        _register_profile(config_path, _local_registration_entry(dict(preview["profile"])))
    except ValueError as exc:
        return {
            "status": "blocked",
            "summary": str(exc),
            "code": "project_registration_conflict",
            "written": written,
            "skipped": skipped,
        }
    return {
        "status": "completed",
        "summary": f"项目接入完成：写入 {len(written)} 个文件，保留 {len(skipped)} 个文件。",
        "plan_hash": plan_hash,
        "profile": preview["profile"],
        "written": written,
        "skipped": skipped,
        "warnings": preview["warnings"],
        "workflow_initialization": preview.get("workflow_initialization", {}),
    }


def onboarding_doctor(profile: ProjectProfile) -> Dict[str, Any]:
    checks: list[Dict[str, Any]] = []
    root = profile.root_dir
    _add_check(checks, "project_root", root.is_dir(), f"项目目录：{root}")
    manifest = _load_manifest()
    profiles = manifest.get("profiles") if isinstance(manifest.get("profiles"), dict) else {}
    profile_manifest = profiles.get(profile.project_type)
    _add_check(
        checks,
        "project_type",
        isinstance(profile_manifest, dict),
        f"项目类型：{profile.project_type or '未配置'}",
    )
    if isinstance(profile_manifest, dict):
        evidence = _profile_evidence(root, profile.project_type)
        _add_check(checks, "profile_evidence", bool(evidence["matched"]), str(evidence["summary"]))
        expected = {str(entry["path"]): entry for entry in _profile_file_entries(profile_manifest)}
        for rel, file_entry in sorted(expected.items()):
            path = root / rel
            ok = path.is_file()
            if ok and file_entry.get("executable"):
                ok = bool(path.stat().st_mode & 0o111)
            if ok and rel == "AGENTS.md":
                agents_text = path.read_text(encoding="utf-8")
                required_links = _required_agent_docs(str(profile_manifest["fifth_doc"]))
                ok = all(link in agents_text for link in required_links)
            if ok and rel.startswith("agent_docs/"):
                ok = not bool(re.search(r"\{\{[A-Z0-9_]+\}\}|\{[A-Z0-9_]+\}", path.read_text(encoding="utf-8")))
            _add_check(checks, f"file:{rel}", ok, f"接入文件：{rel}")

    storage_ready = uses_v2_storage(profile)
    _add_check(
        checks,
        "task_storage",
        storage_ready,
        "data/tasks 单任务 JSON 存储已就绪。" if storage_ready else "项目尚未使用 data/tasks 单任务 JSON 存储。",
    )
    sync_blocker = read_sync_blocker(profile)
    _add_check(
        checks,
        "task_sync",
        sync_blocker is None,
        "任务 Git 同步正常。" if sync_blocker is None else f"任务同步阻塞：{sync_blocker.get('task_id')}",
    )

    legacy_writers = [
        rel
        for rel in (
            "scripts/claim_next.py",
            "scripts/sync_external_task.py",
            "scripts/loopforge_runner.py",
        )
        if (root / rel).exists()
    ]
    _add_check(
        checks,
        "single_dev_task_writer",
        not legacy_writers,
        "未发现项目内第二 writer。" if not legacy_writers else "发现旧 Dev Task writer：" + ", ".join(legacy_writers),
    )

    adapter = str(profile.planning_adapter or "builtin").strip() or "builtin"
    _add_check(
        checks,
        "planning_adapter",
        bool(adapter),
        "builtin planning 已配置。" if adapter == "builtin" else f"外部 planning adapter 已登记：{adapter}；其内部目录不由 LoopForge 检查。",
    )
    if profile.project_type == "project-group":
        children = profile.project_group.get("children") if isinstance(profile.project_group, dict) else None
        child_paths_valid = isinstance(children, list) and bool(children)
        if isinstance(children, list):
            for child in children:
                if not isinstance(child, dict) or not child.get("key"):
                    child_paths_valid = False
                    break
                child_path = Path(str(child.get("path") or child.get("root_dir") or child.get("repo_path") or "")).expanduser()
                if not child_path.is_absolute():
                    child_path = root / child_path
                if not child_path.is_dir():
                    child_paths_valid = False
                    break
        _add_check(checks, "project_group_children", child_paths_valid, "项目组必须登记至少一个可访问子仓。")
    if isinstance(profile_manifest, dict):
        _add_dependency_checks(checks, root, profile_manifest)
    for warning in _quality_warnings(root, profile.project_type, profile_manifest if isinstance(profile_manifest, dict) else None):
        check_status = "failed" if warning["code"] == "quality_command_missing" else "warning"
        checks.append({"id": warning["code"], "status": check_status, "summary": warning["summary"]})

    failed = [check for check in checks if check["status"] == "failed"]
    return {
        "status": "misconfigured" if failed else "completed",
        "summary": f"doctor 发现 {len(failed)} 个问题。" if failed else "doctor 检查通过。",
        "valid": not failed,
        "project_id": profile.project_id,
        "project_type": profile.project_type,
        "checks": checks,
    }


def _preview_result(
    root: Path,
    project_type: str,
    profile_manifest: Dict[str, Any],
    files: list[Dict[str, Any]],
    blockers: list[Dict[str, str]],
    profile_draft: Dict[str, Any],
    planning_adapter: str,
    *,
    evidence: Dict[str, Any] | None = None,
    build_target: str = "",
    owner: str = "",
    workflow_initialization: Dict[str, Any] | None = None,
) -> Dict[str, Any]:
    public_files = [dict(entry) for entry in files]
    plan_material = {
        "root": str(root.resolve()) if root.exists() else str(root),
        "project_type": project_type,
        "profile": profile_draft,
        "planning_adapter": planning_adapter,
        "owner": owner,
        "workflow_initialization": workflow_initialization or {},
        "build_target": build_target,
        "files": [
            {key: entry.get(key) for key in ("path", "action", "current_hash", "desired_hash")}
            for entry in files
        ],
    }
    plan_hash = _digest(json.dumps(plan_material, ensure_ascii=False, sort_keys=True, separators=(",", ":")))
    warnings = [
        {"code": "existing_file_preserved", "path": entry["path"], "summary": "现有非受管文件不会被覆盖。"}
        for entry in files
        if entry["action"] == "skip"
    ]
    return {
        "status": "blocked" if blockers else "completed",
        "summary": f"onboarding 预检发现 {len(blockers)} 个阻塞。" if blockers else "onboarding 预检完成，等待确认生成。",
        "project_type": project_type,
        "profile_label": profile_manifest.get("label") if isinstance(profile_manifest, dict) else "",
        "profile": profile_draft,
        "planning_adapter": planning_adapter,
        "owner": owner,
        "workflow_initialization": workflow_initialization or {},
        "build_target": build_target,
        "evidence": evidence or {},
        "files": public_files,
        "warnings": warnings,
        "blockers": blockers,
        "plan_hash": plan_hash,
    }


def _profile_file_entries(profile: Dict[str, Any]) -> list[Dict[str, Any]]:
    raw = profile.get("files")
    if not isinstance(raw, list) or not raw:
        raise ValueError(f"onboarding profile {profile.get('type') or 'unknown'} 缺少 files 清单")
    entries: list[Dict[str, Any]] = []
    seen: set[str] = set()
    for item in raw:
        if not isinstance(item, dict):
            raise ValueError("onboarding profile files 必须是对象列表")
        rel = str(item.get("path") or "").strip()
        template = str(item.get("template") or "").strip()
        if not rel or not template or rel in seen:
            raise ValueError(f"onboarding profile 文件声明无效或重复：{rel or '<empty>'}")
        seen.add(rel)
        entries.append({**item, "path": rel, "template": template})
    return entries


def _desired_files(profile: Dict[str, Any], variables: Dict[str, str]) -> Dict[str, str]:
    return {
        str(entry["path"]): _render(str(entry["template"]), variables)
        for entry in _profile_file_entries(profile)
    }


def _dependency_file_entry(
    root: Path,
    profile: Dict[str, Any],
    blockers: list[Dict[str, str]],
) -> Dict[str, Any] | None:
    contract = profile.get("dependency_contract")
    if not isinstance(contract, dict):
        return None
    rel = str(contract.get("path") or "").strip()
    kind = str(contract.get("kind") or "").strip()
    if not rel:
        raise ValueError(f"onboarding profile {profile.get('type')} 的 dependency_contract 缺少 path")
    try:
        path = resolve_project_path(root, rel)
    except ProjectPathError as exc:
        blockers.append(_blocker("onboarding_path_outside_project", str(exc), rel))
        return None
    current = _read_optional(path)
    if current is None:
        blockers.append(_blocker("dependency_manifest_missing", f"缺少依赖清单：{rel}", rel))
        return None
    if kind == "go-mod":
        desired = _merge_go_mod(current, contract)
    elif kind == "package-json":
        desired = _merge_package_json(current, contract, blockers, rel)
    else:
        raise ValueError(f"onboarding profile {profile.get('type')} 的 dependency_contract kind 无效：{kind}")
    return {
        "path": rel,
        "action": "unchanged" if desired == current else "update",
        "current_hash": _digest(current),
        "desired_hash": _digest(desired),
        "content": desired,
        "executable": False,
        "management": "dependency",
    }


def _merge_go_mod(current: str, contract: Dict[str, Any]) -> str:
    requirements = contract.get("requires")
    if not isinstance(requirements, dict):
        raise ValueError("go-mod dependency_contract 缺少 requires")
    missing: list[tuple[str, str]] = []
    for module, version in requirements.items():
        clean_module = str(module).strip()
        clean_version = str(version).strip()
        if not clean_module or not clean_version:
            raise ValueError("go-mod dependency_contract 包含空 module 或 version")
        pattern = rf"(?m)^\s*(?:require\s+)?{re.escape(clean_module)}\s+\S+"
        if not re.search(pattern, current):
            missing.append((clean_module, clean_version))
    if not missing:
        return current
    newline = "\r\n" if "\r\n" in current else "\n"
    block = ["require ("]
    block.extend(f"\t{module} {version}" for module, version in missing)
    block.append(")")
    return current.rstrip("\r\n") + newline * 2 + newline.join(block) + newline


def _merge_package_json(
    current: str,
    contract: Dict[str, Any],
    blockers: list[Dict[str, str]],
    rel: str,
) -> str:
    try:
        package = json.loads(current)
    except json.JSONDecodeError as exc:
        blockers.append(_blocker("dependency_manifest_invalid", f"package.json 不是合法 JSON：{exc}", rel))
        return current
    if not isinstance(package, dict):
        blockers.append(_blocker("dependency_manifest_invalid", "package.json 必须是 JSON object。", rel))
        return current

    changed = False
    all_dependencies: set[str] = set()
    for section_name in ("dependencies", "devDependencies"):
        section = package.get(section_name)
        if isinstance(section, dict):
            all_dependencies.update(str(name) for name in section)

    for section_name in ("dependencies", "devDependencies"):
        required = contract.get(section_name)
        if not isinstance(required, dict):
            continue
        section = package.get(section_name)
        if section is None:
            section = {}
            package[section_name] = section
            changed = True
        if not isinstance(section, dict):
            blockers.append(_blocker("dependency_manifest_invalid", f"package.json 的 {section_name} 必须是 object。", rel))
            continue
        for name, version in required.items():
            if str(name) in all_dependencies:
                continue
            section[str(name)] = str(version)
            all_dependencies.add(str(name))
            changed = True

    required_scripts = contract.get("scripts")
    if isinstance(required_scripts, dict):
        scripts = package.get("scripts")
        if scripts is None:
            scripts = {}
            package["scripts"] = scripts
            changed = True
        if not isinstance(scripts, dict):
            blockers.append(_blocker("dependency_manifest_invalid", "package.json 的 scripts 必须是 object。", rel))
        else:
            for name, command in required_scripts.items():
                current_command = scripts.get(name)
                if current_command is None:
                    scripts[str(name)] = str(command)
                    changed = True
                elif str(current_command).strip() != str(command).strip():
                    blockers.append(
                        _blocker(
                            "dependency_script_conflict",
                            f"package.json 脚本 {name} 已存在且与模板不兼容；保留现有命令并停止 apply。",
                            rel,
                        )
                    )

    if not changed:
        return current
    newline = "\r\n" if "\r\n" in current else "\n"
    indent_match = re.search(r"\n([ \t]+)\S", current)
    indent = indent_match.group(1) if indent_match else "  "
    rendered = json.dumps(package, ensure_ascii=False, indent=indent)
    return rendered.replace("\n", newline) + newline


def _dependency_warnings(files: list[Dict[str, Any]], project_type: str) -> list[Dict[str, str]]:
    changed = any(
        entry.get("management") == "dependency" and entry.get("action") == "update"
        for entry in files
    )
    if not changed:
        return []
    if project_type == "go-backend":
        summary = "go.mod 将写入固定栈依赖；apply 后运行 scripts/setup.sh 更新 go.sum。"
    elif project_type == "react-frontend":
        summary = "package.json 将写入固定栈依赖；apply 后运行 scripts/setup.sh --refresh-lock 更新权威锁文件。"
    else:
        return []
    return [{"code": "dependency_setup_required", "summary": summary}]


def _profile_evidence(root: Path, project_type: str) -> Dict[str, Any]:
    if project_type == "project-group":
        return {"matched": True, "signals": [], "summary": "项目组类型由用户显式选择。"}
    if not root.exists():
        return {"matched": False, "signals": [], "summary": "项目目录不存在，无法验证类型。"}
    if project_type == "go-backend":
        matched = (root / "go.mod").is_file()
        return _evidence(matched, ["go.mod"] if matched else [], "缺少 go.mod，不能按 Go 后端项目生成。")
    if project_type == "react-frontend":
        package = _read_json(root / "package.json")
        dependencies = {}
        if isinstance(package, dict):
            dependencies.update(package.get("dependencies") if isinstance(package.get("dependencies"), dict) else {})
            dependencies.update(package.get("devDependencies") if isinstance(package.get("devDependencies"), dict) else {})
        matched = "react" in dependencies
        return _evidence(matched, ["package.json:react"] if matched else [], "package.json 未声明 react，不能按 React 前端项目生成。")
    if project_type == "flutter-app":
        pubspec = _read_optional(root / "pubspec.yaml") or ""
        matched = bool(re.search(r"(?m)^\s*flutter:\s*$", pubspec) and "sdk: flutter" in pubspec)
        return _evidence(matched, ["pubspec.yaml:flutter"] if matched else [], "pubspec.yaml 未声明 Flutter SDK，不能按 Flutter App 生成。")
    if project_type == "java-backend":
        markers = [
            name
            for name in ("pom.xml", "build.gradle.kts", "build.gradle", "settings.gradle.kts", "settings.gradle")
            if (root / name).is_file()
        ]
        return _evidence(bool(markers), markers, "未发现 pom.xml 或 Gradle 构建文件，不能按 Java 后端项目生成。")
    if project_type == "python-scripts":
        markers = [path.name for path in (root / "pyproject.toml", root / "requirements.txt", root / "setup.py") if path.is_file()]
        if not markers:
            markers = [path.name for path in root.glob("*.py") if path.is_file()][:5]
        return _evidence(bool(markers), markers, "未发现 Python 项目标记或脚本，不能按 Python 脚本项目生成。")
    return {"matched": False, "signals": [], "summary": f"不支持的项目类型：{project_type}"}


def _evidence(matched: bool, signals: list[str], missing_summary: str) -> Dict[str, Any]:
    return {"matched": matched, "signals": signals, "summary": "项目类型证据匹配。" if matched else missing_summary}


def _quality_warnings(
    root: Path,
    project_type: str,
    profile_manifest: Dict[str, Any] | None = None,
    *,
    build_target: str = "",
) -> list[Dict[str, str]]:
    if project_type == "react-frontend":
        package = _read_json(root / "package.json")
        scripts = package.get("scripts") if isinstance(package, dict) and isinstance(package.get("scripts"), dict) else {}
        required = ("format", "format:check", "lint", "test", "build")
        missing = [name for name in required if not str(scripts.get(name) or "").strip()]
        if missing:
            return [
                {
                    "code": "quality_command_missing",
                    "summary": "package.json 缺少脚本：" + ", ".join(missing) + "；包装脚本会明确失败，需在自动执行前补齐。",
                }
            ]
    if project_type == "project-group":
        placeholder = "请在项目组配置中声明各子仓"
        manifest = profile_manifest or {}
        script_paths = [
            str(entry["path"])
            for entry in _profile_file_entries(manifest)
            if str(entry["path"]).startswith("scripts/")
        ]
        has_placeholder = any(
            placeholder in (_read_optional(root / rel) or "")
            for rel in script_paths
        )
        if has_placeholder:
            return [
                {
                    "code": "project_group_quality_commands_required",
                    "summary": "项目组聚合质量脚本仍是接入占位实现；请声明子仓命令后再启用自动执行。",
                }
            ]
    if project_type == "go-backend" and not _go_quality_tools_ready(root):
        return [
            {
                "code": "go_quality_tools_verify",
                "summary": "项目本地 goimports/golangci-lint 尚未就绪；启用自动执行前请运行 scripts/setup-tools.sh。",
            }
        ]
    if project_type == "python-scripts":
        return [
            {
                "code": "python_quality_tools_verify",
                "summary": "请先运行 scripts/setup-tools.sh，在项目虚拟环境中准备 Ruff。",
            }
        ]
    configured_flutter_target = bool(
        re.search(
            r'BUILD_TARGET="\$\{1:-[^}"]+\}"',
            _read_optional(root / "scripts" / "build.sh") or "",
        )
    )
    if (
        project_type == "flutter-app"
        and not build_target
        and not _detect_flutter_build_target(root)
        and not configured_flutter_target
    ):
        return [
            {
                "code": "flutter_build_target_required",
                "summary": "未能唯一确定 Flutter 构建平台；运行 scripts/build.sh 时必须显式传入 build target。",
            }
        ]
    if project_type == "java-backend" and not (root / "mvnw").is_file() and not (root / "gradlew").is_file():
        return [
            {
                "code": "java_wrapper_recommended",
                "summary": "未发现 mvnw 或 gradlew；生成脚本会回退系统 Maven/Gradle，建议提交官方 Wrapper。",
            }
        ]
    return []


def _go_quality_tools_ready(root: Path) -> bool:
    tool_env = _read_optional(root / "scripts" / "tool-env.sh") or ""
    requirements = (
        ("goimports", "GOIMPORTS_VERSION"),
        ("golangci-lint", "GOLANGCI_LINT_VERSION"),
    )
    for tool_name, version_var in requirements:
        match = re.search(
            rf'^{version_var}="\$\{{{version_var}:-([^}}]+)\}}"$',
            tool_env,
            re.MULTILINE,
        )
        if not match:
            return False
        expected = match.group(1)
        binary = root / ".tools" / "bin" / tool_name
        version_file = root / ".tools" / f"{tool_name}.version"
        if not binary.is_file() or not bool(binary.stat().st_mode & 0o111):
            return False
        if (_read_optional(version_file) or "").strip() != expected:
            return False
    return True


def _add_dependency_checks(checks: list[Dict[str, Any]], root: Path, profile_manifest: Dict[str, Any]) -> None:
    contract = profile_manifest.get("dependency_contract")
    if not isinstance(contract, dict):
        return
    kind = str(contract.get("kind") or "")
    rel = str(contract.get("path") or "")
    content = _read_optional(root / rel) or ""
    if kind == "go-mod":
        requirements = contract.get("requires") if isinstance(contract.get("requires"), dict) else {}
        for module in requirements:
            present = bool(re.search(rf"(?m)^\s*(?:require\s+)?{re.escape(str(module))}\s+\S+", content))
            _add_check(checks, f"dependency:{module}", present, f"go.mod 固定栈依赖：{module}")
        return
    if kind != "package-json":
        return
    package = _read_json(root / rel)
    package = package if isinstance(package, dict) else {}
    dependencies: Dict[str, Any] = {}
    for section_name in ("dependencies", "devDependencies"):
        section = package.get(section_name)
        if isinstance(section, dict):
            dependencies.update(section)
    for section_name in ("dependencies", "devDependencies"):
        required = contract.get(section_name) if isinstance(contract.get(section_name), dict) else {}
        for name in required:
            _add_check(checks, f"dependency:{name}", str(name) in dependencies, f"package.json 固定栈依赖：{name}")
    scripts = package.get("scripts") if isinstance(package.get("scripts"), dict) else {}
    required_scripts = contract.get("scripts") if isinstance(contract.get("scripts"), dict) else {}
    for name, command in required_scripts.items():
        ready = str(scripts.get(name) or "").strip() == str(command).strip()
        _add_check(checks, f"dependency:script:{name}", ready, f"package.json 标准脚本：{name}")


def _profile_draft(
    root: Path,
    project_id: str,
    name: str,
    project_type: str,
    planning_adapter: str,
    group_children: list[Dict[str, str]],
) -> Dict[str, Any]:
    resolved = root.resolve()
    draft = {
        "id": project_id,
        "name": name,
        "root_dir": str(resolved),
        "project_type": project_type,
        "planning_adapter": planning_adapter,
        "enabled": True,
        "schedule_enabled": False,
        "automation_mode": "off",
        "auto_commit": False,
        "worktree_managed": True,
        "default_agent": "codex",
        "executor": "codex_cli",
        "notification_channel": "none",
        "state_dir": str(resolved / ".loopforge"),
        "report_dir": str(resolved / ".loopforge" / "reports"),
    }
    if project_type == "project-group":
        draft["project_group"] = {"key": project_id, "children": group_children}
    return draft


def _tracked_project_config_entry(root: Path, project_type: str) -> Dict[str, Any]:
    payload: Dict[str, Any] = {
        "schema_version": 1,
        "project_type": project_type,
    }
    content = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    path = root / ".loopforge" / "project.json"
    current = _read_optional(path)
    action = "create" if current is None else "unchanged" if current == content else "skip"
    return {
        "path": ".loopforge/project.json",
        "action": action,
        "current_hash": _digest(current or ""),
        "desired_hash": _digest(content),
        "content": content,
        "executable": False,
        "management": "seed",
    }


def _local_registration_entry(entry: Dict[str, Any]) -> Dict[str, Any]:
    local = dict(entry)
    local.pop("project_type", None)
    local.pop("bdd", None)
    return local


def _detect_project_group_children(root: Path) -> list[Dict[str, str]]:
    if not root.is_dir():
        return []
    children: list[Dict[str, str]] = []
    for child in sorted(root.iterdir(), key=lambda path: path.name):
        if not child.is_dir() or not (child / ".git").exists():
            continue
        children.append({"key": child.name, "path": str(child.resolve()), "repo": child.name})
    return children


def _normalize_project_group_children(
    root: Path,
    raw_children: list[Dict[str, Any]],
    blockers: list[Dict[str, str]],
) -> list[Dict[str, str]]:
    children: list[Dict[str, str]] = []
    seen: set[str] = set()
    for index, raw in enumerate(raw_children):
        payload = raw if isinstance(raw, dict) else {}
        key = str(payload.get("key") or payload.get("id") or "").strip()
        path_value = str(payload.get("path") or payload.get("root_dir") or "").strip()
        if not key or not path_value:
            blockers.append(_blocker("project_group_child_invalid", f"第 {index + 1} 个子仓必须提供 key 和 path。"))
            continue
        if key in seen:
            blockers.append(_blocker("project_group_child_duplicate", f"项目组子仓 key 重复：{key}"))
            continue
        seen.add(key)
        path = Path(path_value).expanduser()
        if not path.is_absolute():
            path = root / path
        path = path.resolve()
        if not path.is_dir() or not (path / ".git").exists():
            blockers.append(_blocker("project_group_child_not_git", f"项目组子仓不是可用 Git 仓库：{path}"))
            continue
        children.append({"key": key, "path": str(path), "repo": str(payload.get("repo") or path.name)})
    return children


def _register_profile(config_path: Path | None, entry: Dict[str, Any]) -> None:
    payload = read_projects_config(config_path)
    projects = payload.setdefault("projects", [])
    if not isinstance(projects, list):
        raise ValueError("projects 配置必须是列表")
    entry_root = Path(str(entry["root_dir"])).resolve()
    for current in projects:
        if not isinstance(current, dict):
            continue
        current_id = str(current.get("id") or current.get("project_id") or "")
        current_root_value = current.get("root_dir") or current.get("root")
        current_root = Path(str(current_root_value)).expanduser().resolve() if current_root_value else None
        if current_id == entry["id"] and current_root == entry_root:
            current.pop("project_type", None)
            current.pop("bdd", None)
            registration_keys = (
                "name",
                "planning_adapter",
                "automation_mode",
                "schedule_enabled",
                "auto_commit",
                "worktree_managed",
            )
            current.update({key: entry[key] for key in registration_keys if key in entry})
            if "project_group" in entry:
                current["project_group"] = entry["project_group"]
            write_projects_config(payload, config_path)
            return
        if current_id == entry["id"]:
            raise ValueError(f"项目 id 已被其他目录占用：{entry['id']}")
        if current_root == entry_root:
            raise ValueError(f"项目目录已登记为其他项目：{current_id}")
    projects.append(entry)
    write_projects_config(payload, config_path)


def _validate_registration(config_path: Path | None, entry: Dict[str, Any]) -> None:
    payload = read_projects_config(config_path)
    projects = payload.get("projects")
    if not isinstance(projects, list):
        raise ValueError("projects 配置必须是列表")
    entry_root = Path(str(entry["root_dir"])).resolve()
    for current in projects:
        if not isinstance(current, dict):
            continue
        current_id = str(current.get("id") or current.get("project_id") or "")
        current_root_value = current.get("root_dir") or current.get("root")
        current_root = Path(str(current_root_value)).expanduser().resolve() if current_root_value else None
        if current_id == entry["id"] and current_root != entry_root:
            raise ValueError(f"项目 id 已被其他目录占用：{entry['id']}")
        if current_root == entry_root and current_id != entry["id"]:
            raise ValueError(f"项目目录已登记为其他项目：{current_id}")


def _required_agent_docs(fifth_doc: str) -> tuple[str, ...]:
    return (
        "agent_docs/ARCH.md",
        "agent_docs/BUILD.md",
        "agent_docs/TEST.md",
        "agent_docs/DEV_TASK_EXECUTION.md",
        f"agent_docs/{fifth_doc}",
    )


def _reconcile_agents(current: str | None, generated: str, required_docs: tuple[str, ...]) -> str:
    if current is None or not current.strip():
        return generated
    legacy_pattern = re.compile(
        re.escape(LEGACY_AGENTS_START) + r".*?" + re.escape(LEGACY_AGENTS_END),
        re.DOTALL,
    )
    without_legacy = legacy_pattern.sub("", current)
    if without_legacy != current:
        without_legacy = re.sub(r"\n{3,}", "\n\n", without_legacy).strip()
        if not without_legacy:
            return generated
        base = without_legacy + "\n"
    else:
        base = current
    missing = [path for path in required_docs if path not in base]
    if not missing:
        return base
    lines = ["## Agent 文档路由", "", "修改代码前，按任务涉及范围补充阅读：", ""]
    lines.extend(f"- `{path}`" for path in missing)
    lines.extend(
        [
            "",
            "Dev Task 的详细执行合同只在 `agent_docs/DEV_TASK_EXECUTION.md` 维护，本文件不重复字段与状态规则。",
        ]
    )
    return base.rstrip() + "\n\n" + "\n".join(lines) + "\n"


def _load_manifest() -> Dict[str, Any]:
    profiles: Dict[str, Any] = {}
    for path in sorted(TEMPLATE_ROOT.glob("*/manifest.json")):
        profile = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(profile, dict):
            raise ValueError(f"onboarding manifest 必须是对象：{path}")
        profile_type = str(profile.get("type") or path.parent.name).strip()
        if profile_type != path.parent.name or profile_type in profiles:
            raise ValueError(f"onboarding profile 类型与目录不一致或重复：{profile_type}")
        profile["type"] = profile_type
        profiles[profile_type] = profile
    return {"version": 2, "profiles": profiles}


def _render(relative_template: str, variables: Dict[str, str]) -> str:
    template_path = (TEMPLATE_ROOT / relative_template).resolve()
    if not template_path.is_relative_to(TEMPLATE_ROOT.resolve()):
        raise ValueError(f"模板路径越界：{relative_template}")
    text = template_path.read_text(encoding="utf-8")
    for key, value in variables.items():
        text = text.replace("{{" + key + "}}", value)
    unresolved = re.findall(r"\{\{[A-Z0-9_]+\}\}", text)
    if unresolved:
        raise ValueError(f"模板存在未替换变量：{', '.join(sorted(set(unresolved)))}")
    return text.rstrip() + "\n"


def _is_generated(content: str) -> bool:
    return any(marker in content for marker in GENERATED_MARKERS)


def _detect_package_manager(root: Path) -> str:
    package = _read_json(root / "package.json")
    declared = str(package.get("packageManager") or "") if isinstance(package, dict) else ""
    if declared:
        return declared.split("@", 1)[0]
    for marker, manager in (("pnpm-lock.yaml", "pnpm"), ("yarn.lock", "yarn"), ("package-lock.json", "npm")):
        if (root / marker).is_file():
            return manager
    return "npm"


def _detect_flutter_build_target(root: Path) -> str:
    targets = [name for name in ("android", "web", "ios", "macos", "linux", "windows") if (root / name).is_dir()]
    if len(targets) != 1:
        return ""
    return {"android": "apk", "web": "web"}.get(targets[0], targets[0])


def _detect_java_build_tool(root: Path) -> str:
    if (root / "mvnw").is_file() or (root / "pom.xml").is_file():
        return "maven"
    if any((root / name).is_file() for name in ("gradlew", "build.gradle.kts", "build.gradle")):
        return "gradle"
    return ""


def _resolve_planning_adapter(root: Path, explicit: str, blockers: list[Dict[str, str]]) -> str:
    selected = str(explicit or "").strip() or DEFAULT_PLANNING_ADAPTER
    if selected not in PLANNING_ADAPTERS:
        blockers.append(
            _blocker(
                "planning_adapter_invalid",
                "不支持的研发工作流：" + selected + "；可选值：" + ", ".join(sorted(PLANNING_ADAPTERS)),
            )
        )
        return selected
    return selected


def _workflow_initialization(root: Path, planning_adapter: str, owner: str) -> Dict[str, Any]:
    return {
        "provider": planning_adapter,
        "action": "none",
        "command": [],
        "spec_template": "default",
        "ai_tools": [],
    }


def _read_optional(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None


def _read_json(path: Path) -> Any:
    raw = _read_optional(path)
    if raw is None:
        return None
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return None


def _digest(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _slug(value: str) -> str:
    clean = re.sub(r"[^a-zA-Z0-9_-]+", "-", str(value).strip()).strip("-").lower()
    return clean or "project"


def _blocker(code: str, summary: str, path: str = "") -> Dict[str, str]:
    blocker = {"code": code, "summary": summary}
    if path:
        blocker["path"] = path
    return blocker


def _add_check(checks: list[Dict[str, Any]], check_id: str, passed: bool, summary: str) -> None:
    checks.append({"id": check_id, "status": "passed" if passed else "failed", "summary": summary})
