<!-- Generated by LoopForge onboarding v2; seed -->
# {{PROJECT_NAME}} Flutter 架构约束

## 边界

本文定义 Dart 共享代码、feature、平台实现和依赖方向；页面流程与业务协议写入模块 `docs/*`。

```text
screen/widget → feature/state → domain/usecase → repository/service → platform/network/storage
```

- Widget 负责渲染和输入转发，不直接编排网络、数据库或平台通道。
- 状态管理沿用项目现有方案；不得因模板引入新的 Provider/BLoC/Riverpod 等框架。
- domain/usecase 保持 Dart 可测试性，不依赖具体 Widget、插件或平台工程。
- repository/service 负责 DTO 转换、缓存策略和失败归一。
- MethodChannel、插件封装和 `android/ios/...` 代码位于平台边界。

## 生命周期

- 异步回调在更新 UI 前确认对象仍有效；subscription、controller 和 observer 必须释放。
- 导航参数、deep link 和恢复状态需要明确校验与缺失路径。
- 不在 build 方法创建长期资源或触发不可控副作用。

## 平台差异

共享实现不得假设 Android/iOS/Web 能力完全一致。权限、文件系统、通知、后台执行和安全存储必须按目标平台记录降级策略。

## 禁止事项

- 业务页面直接读取 secrets 或平台凭证。
- 在多个 feature 复制同一 DTO 和错误映射。
- 手改生成代码而不修改源 schema/生成器。
