<!-- Generated by LoopForge onboarding v2; seed -->
# {{PROJECT_NAME}} Flutter 构建与运行

## 标准入口

```text
scripts/setup.sh
scripts/format.sh
scripts/format-check.sh
scripts/lint.sh
scripts/test.sh
scripts/build.sh [build-target]
```

默认构建目标探测结果为 `{{FLUTTER_BUILD_TARGET}}`。为空表示项目包含多个或没有明确平台，调用 `build.sh` 时必须传入 `apk`、`appbundle`、`web`、`ios`、`macos`、`linux` 或 `windows` 等项目支持的目标。

## 环境

- Flutter/Dart 版本以项目已提交的版本管理配置和 `pubspec.yaml` SDK 约束为准。
- `scripts/flutter-env.sh` 只检查工具可用性，不自动升级 SDK。
- 依赖使用 `flutter pub get`；更新依赖必须审查 `pubspec.yaml` 和 lockfile。
- flavor、签名、bundle id 和环境变量属于项目配置，不由通用模板创建。

## 安全边界

- 构建脚本不发布商店、不上传制品、不执行签名和远端部署。
- keystore、证书、provisioning profile 和真实 API key 不进入仓库。
- 生成目录和构建产物不作为源码编辑目标。

修改 SDK、平台目标、flavor 或 codegen 时，同步本文、脚本和 CI。
