<!-- Generated by LoopForge onboarding v2; seed -->
# {{PROJECT_NAME}} Flutter 测试约束

## 最低门禁

源码改动至少运行 format-check、analyze、test 和适用平台 build。只影响单个平台时仍需确认共享 Dart 代码未破坏其他目标。

## 测试分层

- Unit：domain、usecase、转换和状态对象，不依赖 Flutter binding。
- Widget：真实 Widget 的布局语义、输入、loading/empty/error 和导航触发。
- Integration：关键页面流、插件边界和真实框架生命周期，使用隔离后端或确定性 fake。
- Platform：权限、通知、存储、deep link 等需要在目标平台或可靠模拟器验证。

## 编写规则

- 断言用户可观察结果，避免依赖 Widget 私有层级和实现细节。
- `pumpAndSettle` 不是默认答案；明确等待的动画、任务和退出条件。
- fake clock、网络、存储和平台通道必须在测试结束后恢复。
- 覆盖 mounted/dispose 后异步返回、重复点击、离线、权限拒绝和未知数据。
- golden 测试需固定字体、尺寸、像素比和平台，并人工审查基线变化。

测试失败必须修复并重跑；设备或 SDK 缺失时明确记录未验证平台。
