<!-- Generated by LoopForge onboarding v2; seed -->
# {{PROJECT_NAME}} Go 架构约束

> 负责：运行入口、目录、分层职责、依赖方向、adapter、协议边界和生成代码边界。
>
> 不负责：具体业务规则、业务字段、权限点、状态枚举和 API payload；这些事实进入 `docs/<module>/requirements.md|design.md|specs.md`。

## 1. 定位与原则

本仓库固定使用 Go + Gin + GORM。现有业务入口优先于模板示例；目录只在承担真实职责时创建。

核心原则：

- 领域优先：包名表达业务能力或明确技术职责。
- 依赖单向：稳定业务层依赖抽象，不依赖数据库、Web 框架和第三方 SDK 的具体实现。
- 边界明确：进程入口、依赖装配、用例编排、领域规则和技术实现分离。
- 显式装配：依赖通过构造函数传入，避免全局可变单例和隐式 `init` 副作用。
- 变更先行：突破本文边界前先更新架构文档并说明原因。

## 2. 推荐目录映射

项目可以沿用已有命名，但职责应能映射到以下结构：

```text
cmd/                 # 进程入口
internal/
  bootstrap/         # 配置读取、依赖装配和启动
  platform/          # 无业务语义的基础设施
  domain/            # 实体、值对象和纯领域规则
  service/           # 单领域业务服务
  app/               # 跨领域或跨外部能力的用例编排
  ports/             # repository、cache、external 等出站接口
  adapters/          # HTTP、DB、消息、缓存、第三方实现
  jobs/              # 定时任务和后台作业编排
contracts/           # 可选的外部协议或生成源
configs/             # 可提交的非敏感配置样例
test/integration/    # 带 integration build tag 的集成测试
```

没有对应能力时不创建空目录。小型项目可以合并层次，但不能合并职责边界。

## 3. 分层职责

| 层 | 职责 | 禁止 |
| --- | --- | --- |
| `cmd` | 解析进程参数并调用 bootstrap | 写业务规则、SQL 或复杂依赖装配 |
| `bootstrap` | 读取配置，装配 adapter/service/app/job 并启动 | 写领域判断、HTTP DTO 转换或查询实现 |
| `platform` | 日志、配置、clock、ID、事务、通用错误等无业务语义设施 | 依赖 domain/app/adapters 或承载业务名词 |
| `domain` | 实体、值对象、纯规则、状态校验和领域错误 | 依赖框架、配置、网络、数据库或 adapter |
| `service` | 单领域校验、状态流转和 repository port 调用 | 直接依赖 adapter，编排无关领域 |
| `app` | 跨领域、跨服务或跨外部能力的流程编排 | 直接写 SQL，把 HTTP DTO 当业务输入输出 |
| `ports` | 定义消费者需要的出站能力接口 | 放实现或泄漏 ORM/SDK 类型 |
| `adapters` | 用 Gin 实现 HTTP、用 GORM 实现 persistence，并承载 cache、external、queue 等技术边界 | 写业务规则，让 Gin/GORM 模型穿透内层 |
| `jobs` | 批次、重试、锁、进度和调度编排 | 直接写 SQL 或修改领域状态 |

接口由消费者侧定义，只为真实替换点创建。单实现、无隔离价值的接口会增加无意义抽象。

## 4. 依赖方向

允许：

```text
cmd -> bootstrap
bootstrap -> platform/adapters/service/app/jobs
adapters -> ports/domain/platform
jobs -> service/app/platform
app -> service/domain/platform
service -> domain/ports/platform
ports -> domain/platform/标准库
domain -> 标准库
platform -> 标准库或无业务语义第三方库
```

禁止：

```text
domain -> service/app/ports/adapters/platform
service -> app/adapters
app -> adapters 或直接调用 persistence 实现
ports -> service/app/adapters
platform -> domain/service/app/adapters
cmd -> 具体业务实现
```

新增跨层依赖前必须说明：调用职责、为什么现有边界不能承载、如何测试、是否导致循环依赖。

## 5. 请求、错误与上下文边界

- HTTP/RPC request/response DTO 属于入站 adapter，不作为 domain 或 service 的长期模型。
- Gin `Context` 只存在于 HTTP adapter；DB row、GORM model 和第三方 SDK response 属于对应 adapter，在边界显式转换。
- `context.Context` 从请求或作业入口向下传递，不保存在长期对象中，也不作为可选参数滥用。
- 内层返回稳定错误和 cause；协议层统一映射状态码、错误码与可公开信息。
- 日志不能替代错误返回；同一错误只在拥有处置语义的边界记录一次。
- 配置在 bootstrap 校验并转换为明确依赖，业务层不直接读取环境变量。

## 6. 并发、事务与外部能力

- goroutine 必须有明确 owner、取消信号、退出条件和错误收集方式。
- 并发数量、队列容量、重试、退避和超时必须有上界。
- 事务由用例或 transaction port 控制，不把 ORM transaction 对象泄漏到业务层。
- 外部调用通过 port 隔离，明确 timeout、幂等、重试条件和不可重试错误。
- 跨系统操作默认不能假设分布式事务；使用已确认的补偿、outbox、checkpoint 或幂等策略。

## 7. 协议与生成代码

- 外部协议的 source of truth 可以是 OpenAPI、Proto、schema 或已批准 specs；生成目标不是事实源。
- 生成文件不得手工编辑，文件头和目录必须清晰标识生成边界。
- 生成器版本、输入、命令和输出位置写入 `BUILD.md`。
- 生成差异与源文件一起 review，防止字段删除、类型漂移或无关格式化。

## 8. 包设计与命名

- 包名使用简短职责名，不使用无边界的 `common`、`utils`、`helper`、`dao`、`model`。
- 同一包内文件按职责拆分，不按“一个函数一个文件”机械切割。
- 导出标识符必须有稳定使用方；不要为测试暴露内部实现。
- 错误、枚举和接口放在拥有语义的包，不建全局杂物包。
- 避免循环依赖、隐式注册、包级可变状态和依赖测试执行顺序。

## 9. 架构变更检查

涉及目录、入口、层次、port 或 adapter 时：

1. 更新本文或对应模块设计。
2. 检查依赖方向和协议模型是否泄漏。
3. 补充边界单测或架构测试。
4. 运行 format、lint、unit test 和 build。
5. 若增加外部资源，再运行对应 integration test。
