<!-- Generated by LoopForge onboarding v2; seed -->
# {{PROJECT_NAME}} Go 构建与运行约束

> 负责：工具链、标准脚本、依赖、配置、构建、运行、生成和 CI 门禁。
>
> 不负责：业务需求、协议字段、数据语义和测试分层；分别由模块文档、`DATA_ENGINEERING.md` 与 `TEST.md` 维护。

## 1. 工具链

- Go 版本以 `go.mod` 或 `go.work` 为准，不在文档中维护第二份版本号。
- 格式化使用 `gofmt + goimports`，lint 使用项目根目录 `.golangci.yml`。
- `goimports` 和 `golangci-lint` 版本只在 `scripts/tool-env.sh` 声明。
- 工具安装到 `.tools/bin`，不写系统目录，不提交 Git。
- `scripts/format.sh`、`format-check.sh`、`lint.sh` 不隐式联网；缺工具时明确失败并提示运行 `scripts/setup-tools.sh`。
- 调用方显式提供的 `GOPROXY`、`GOSUMDB` 等环境优先于脚本默认值。

## 2. 标准脚本

```text
scripts/setup-tools.sh                 # 安装固定版本项目工具
scripts/setup.sh                       # 下载 go.mod 依赖并准备项目工具
scripts/format.sh                      # gofmt + goimports，会修改源码
scripts/format-check.sh                # 只读格式检查
scripts/lint.sh                        # golangci-lint
scripts/test.sh [unit|integration|all] # 测试分层入口
scripts/build.sh                       # 编译全部 package，不污染仓库
scripts/go-env.sh                      # Go 共享环境，仅供 source
scripts/tool-env.sh                    # 工具目录与版本，仅供 source
```

本地、Agent 和 CI 调用同一组脚本，不在工作流文件中复制长命令。项目增加运行入口、代码生成、迁移、镜像或 E2E 时，应新增职责单一的项目脚本并在本文登记。

## 3. 工具准备与离线环境

首次准备：

```text
scripts/setup.sh
```

- 安装完成后必须同时存在 `.tools/bin/<tool>` 和 `.tools/<tool>.version`。
- 版本 marker 不匹配时视为未准备，不允许悄悄使用全局同名工具。
- 无外网环境应在镜像或缓存准备阶段安装工具；质量门禁阶段不临时下载。
- proxy、DNS 或证书失败必须报告真实错误，不能把缺工具包装成 lint 通过。

## 4. 依赖管理

- 新增依赖前确认标准库或现有依赖不能满足，并审查许可证、维护状态和安全边界。
- 使用 `go mod tidy` 同步 `go.mod`、`go.sum`，必须 review 间接依赖变化。
- 禁止通过手工编辑 `go.sum` 修复依赖问题。
- `replace`、私有 module、toolchain 或 workspace 配置必须在本文说明用途和 CI 条件。
- 依赖升级需运行 format-check、lint、unit test、build；协议或存储依赖还要运行对应 integration test。

## 5. 格式化与 Lint

- `format.sh` 是唯一标准修改入口；`format-check.sh` 只读。
- `.golangci.yml` 固定启用的 linter 集合，项目可基于真实风险增补，不因已有告警随意关闭。
- `//nolint:<name>` 必须指定 linter 和原因，并限制在最小行或函数范围。
- 生成代码如需排除，使用可审查的目录或文件头规则，不写笼统全局排除。

## 6. 测试入口

```text
scripts/test.sh unit
scripts/test.sh integration
scripts/test.sh all
```

- `unit` 执行普通 package 测试，不依赖外部服务。
- `integration` 只执行 `test/integration/...` 且使用 `integration` build tag；目录不存在时安全跳过。
- `all` 依次执行 unit 和 integration，任一步失败立即返回非 0。
- race、coverage、contract 或 E2E 由项目按需要增加显式脚本/参数，不改变默认 unit 语义。

onboarding 会把 Gin、GORM、GORM MySQL driver 与 gorm/gen 的缺失声明写入 `go.mod`；preview/apply 本身不联网。apply 后运行 `scripts/setup.sh`：`go mod download all` 更新 `go.sum`，随后准备固定版本质量工具。不要在基础分层尚未被源码引用时用 `go mod tidy` 删除模板固定依赖。

## 7. 构建与产物

- 通用 `build.sh` 逐 package 编译到 `/dev/null`，只验证可构建性，不猜测二进制名称。
- 通用 build 执行前后不得在项目根目录产生 module 同名二进制或其他未忽略文件。
- 项目有明确 `cmd/*` 入口时，应把发布产物写入已忽略的 `bin/`，并支持显式 target。
- 构建脚本不连接生产数据库、不执行迁移、不发布镜像、不上传制品。
- 版本注入、交叉编译、CGO、容器和发布签名必须形成项目专用合同。

## 8. 配置与运行

- 配置优先级、必填项、默认值和校验时机必须明确；启动时尽早失败。
- 可提交配置只包含安全样例，真实密钥通过环境或部署系统注入。
- `.env`、本地覆盖文件、凭证和生产地址不得提交。
- 项目专用 `run-*.sh` 应明确入口、配置来源、端口、外部依赖和停止方式。
- 启动脚本不得默默使用生产环境或执行破坏性初始化。

## 9. 代码生成与迁移

- 生成器的版本、输入、输出和命令必须固定并可重复执行。
- 生成命令执行后检查 diff；源文件与生成结果一起 review。
- migration 的创建、校验和应用必须分离；通用 build/test 不应用真实数据库迁移。
- 任何生产迁移、回滚或数据修复都需要项目专用流程和人工确认边界。

## 10. 默认 CI 门禁

```text
scripts/setup.sh
scripts/format-check.sh
scripts/lint.sh
scripts/test.sh unit
scripts/build.sh
```

项目存在 integration 环境时追加 `scripts/test.sh integration`。修改生成器、协议、schema 或发布配置时，追加对应项目门禁。

修改工具版本、依赖策略、build tag、生成入口、构建产物或运行入口时，必须同时更新本文、脚本、CI 和相关测试，不能只修一处。
