<!-- Generated by LoopForge onboarding v2; seed -->
# {{PROJECT_NAME}} Go 数据工程约束

> 负责：schema、迁移、repository、事务、数据不变量、敏感数据和生成代码。
>
> 不负责：具体业务实体、状态、权限、API 字段和报表口径；这些事实进入对应模块文档和协议。

## 1. 单一真实来源

- 已批准 DDL、migration 或 schema：字段名、类型、索引、约束和默认值。
- 模块 `requirements/design/specs`：表职责、业务语义、权限、状态和协议口径。
- 本文：跨模块通用的数据工程边界。
- 生成代码和 ORM model 是派生产物，不得反向覆盖 schema 事实。
- persistence adapter 固定使用 GORM；`gorm.io/gen` 输出属于派生代码，只能通过固定生成入口更新，不得手工编辑。

事实冲突时停止猜测，记录冲突并同步修正权威工件。

## 2. 存储与分层边界

- domain、service、app 不依赖 ORM、SQL driver、数据库 row 或具体存储 SDK。
- repository port 位于消费者边界，方法使用领域语言表达意图。
- persistence adapter 负责 SQL/ORM、row 映射、分页实现和存储错误转换。
- HTTP DTO、DB row、cache payload、event payload 与 domain model 分离。
- 不为未来可能使用的数据库提前创建空 repository 或 migration。

## 3. Repository 约束

- 查询明确过滤条件、稳定排序、分页、空结果和上下文取消。
- repository 默认返回稳定的 not-found/conflict 错误，不泄漏 driver error 给协议层。
- 方法避免暴露 query builder、事务句柄、ORM scope 或任意 map 条件。
- 批量读写声明大小上限、顺序、部分失败和幂等行为。
- 缓存不是事实源；缓存失效、击穿和回源策略必须明确。

## 4. 事务边界

- 事务由 app/usecase 或 transaction port 控制，覆盖一个明确业务原子边界。
- 多个 repository 不得各自隐式开启互不相关事务来伪装原子性。
- 事务中避免不可控网络调用和长时间计算；需要时采用 outbox、补偿或 checkpoint。
- 明确隔离级别、锁顺序、冲突重试和 context 取消。
- 错误返回时必须验证 rollback；commit 失败不能包装为成功。

## 5. Schema 与迁移

- migration 可审查、顺序稳定；必须有回滚或清晰前向修复策略。
- 非空、唯一、索引、精度、枚举和默认值变化先说明现有数据兼容与发布顺序。
- 大表变更评估锁表、回填、双写/双读、灰度和旧版本兼容。
- destructive migration、生产执行和数据修复需要项目专用流程与人工确认。
- 测试和通用 build 不连接生产，也不自动应用真实 migration。

## 6. 通用数据不变量

### 6.1 标识与引用

- ID 类型、生成位置和全局/租户作用域必须明确。
- 逻辑引用需要应用层、repository 和测试共同保证；是否使用物理外键由项目 schema 决定。
- 不使用时间戳、数组下标或可变业务名称冒充稳定主键。

### 6.2 时间

- 区分业务发生、接收、处理、入库、更新和过期时间。
- 存储时区与 API 时区必须明确；默认优先 UTC，展示层再转换。
- 测试通过 clock 注入控制时间，不依赖当前机器时钟。

### 6.3 金额、比例与数值

- 精确金额不使用 `float32/float64`；单位、币种、舍入和溢出规则必须明确。
- decimal、比例、计数和持续时间声明精度与单位。
- 聚合和分页排序处理 NULL、零值、负值与边界溢出。

### 6.4 JSON 与扩展字段

- JSON 适合扩展配置和快照，不替代稳定索引、关联和筛选字段。
- JSON 结构变化说明版本、默认值、兼容读取和解析失败处理。
- 高频查询或长期稳定字段应评估提升为显式列。

### 6.5 敏感数据

- 密钥、token 和 credential 只保存安全引用或加密结果，不以明文进入业务表。
- headers、query、body、IP、设备标识等进入持久化前按项目要求脱敏或 hash。
- 日志、错误、fixture、导出和普通列表默认不返回敏感原文。
- 新增敏感字段必须说明保存目的、访问范围、保留期和删除策略。

## 7. 多租户、软删除与审计

这些能力不是所有项目的默认事实；一旦项目采用，必须形成明确合同：

- 多租户查询、唯一键和关联默认包含 tenant scope，跨租户操作显式声明。
- 软删除过滤由 repository 统一处理，删除标记不等于业务状态。
- 审计字段区分操作者、来源、业务时间和系统时间，不用日志替代持久审计。
- 全局表、物理删除和绕过审计必须有项目级例外说明。

## 8. 生成代码

- 生成文件不得手工编辑；修改 schema、模板或生成器后重新生成。
- 生成器版本、输入、命令和输出位置在 `BUILD.md` 登记。
- 生成命令可重复执行，第二次执行不产生非预期 diff。
- 生成差异与源文件一起 review，重点检查字段删除、类型变化、nullable、索引和接口漂移。

## 9. 测试要求

- Unit：领域转换、错误映射、分页参数和 transaction orchestration。
- Integration：真实 schema、SQL/ORM 行为、唯一冲突、rollback、并发更新和 migration。
- Contract：schema/协议 fixture 与生成结果兼容。
- 测试使用隔离资源，禁止生产 DSN、共享数据库和真实敏感数据。

## 10. 数据变更检查

1. 确认字段结构与业务语义各自的权威文档。
2. 评估现有数据、旧版本、索引、锁和发布顺序。
3. 更新 schema/migration、模块文档和生成源。
4. 重新生成并 review diff。
5. 运行 unit、integration、contract 和 build 的适用子集。
6. 记录回滚、前向修复、监控和人工确认边界。
