<!-- Generated by LoopForge onboarding v2; seed -->
# {{PROJECT_NAME}} Go 测试约束

> 负责：测试分层、TDD、fixture、fake/mock、build tag、失败路径和完成门槛。
>
> 不负责：业务需求本身、生产配置和构建产物；测试场景必须从任务验收、模块文档和稳定工程边界导出。

## 1. 质量目标

测试必须证明行为、边界和失败分支，而不是证明 mock 被调用或源码文本没有变化。每个回归测试都要能回答：删除哪段生产行为会让它失败。

源码改动的默认门禁：

```text
scripts/format-check.sh
scripts/lint.sh
scripts/test.sh unit
scripts/build.sh
```

涉及真实 adapter、schema 或外部协议时追加 integration/contract；关键用户路径按项目能力追加 E2E。

## 2. 标准测试模式

```text
scripts/test.sh unit
scripts/test.sh integration
scripts/test.sh all
```

- `unit`：普通 package 测试，必须可离线、可并行、无共享外部资源。
- `integration`：`test/integration/...`，使用 `integration` build tag 和隔离资源。
- `all`：unit 与 integration 顺序执行，任一失败即失败。
- 未建立 integration 目录时显式提示并成功跳过，不创建空占位测试。

## 4. 测试分层

### 4.1 Unit

- 覆盖 domain、值对象、纯转换、状态校验、错误映射和边界条件。
- 不访问网络、真实数据库、系统时间、随机全局源或进程环境。
- 时间、ID、随机和外部能力通过最小接口或参数注入。
- 表驱动测试适合等价输入矩阵；复杂流程按行为拆分，避免巨型 case 表。

### 4.2 Package / Component

- 验证同一 package 内多个真实对象协作。
- 优先真实实现和内存 fake，只有慢或外部边界使用替身。
- 断言组件可观察结果、状态和错误，不断言私有调用顺序。

### 4.3 Integration

- 覆盖 persistence、消息、缓存、HTTP client/server adapter 和代码生成后的实际绑定。
- 使用独立 schema、临时目录、随机端口或专用容器，禁止连接生产和共享开发库。
- 每个测试自行准备并清理数据，不依赖执行顺序。
- 明确 timeout、取消、重试、幂等和资源释放。

### 4.4 Contract

- 覆盖 OpenAPI/Proto/schema、请求响应、错误码、事件结构和兼容性。
- 期望值来自已批准合同的独立 fixture，不调用生产序列化器生成 expected。
- 新字段、默认值和兼容行为必须有 good/base/bad 样例。

### 4.5 E2E / Smoke

- 只覆盖最关键用户路径和部署装配，不复制所有 unit 场景。
- 明确依赖服务、启动停止、测试账户和数据清理方式。
- E2E 失败必须保留可定位日志，但不得泄漏凭证和敏感载荷。

## 5. TDD 与回归测试

行为变更遵循 RED → GREEN → REFACTOR：

1. 先写最小失败测试并确认失败原因正确。
2. 只实现让测试通过的最小行为。
3. 运行相关测试和全量门禁。
4. 通过后再消除重复、改善命名和边界。

Bug 修复必须用原始症状构造回归测试。测试若在修复前已经通过，说明没有捕获问题，应重新设计。

## 6. Good / Base / Bad

每项行为至少判断：

- Good：主路径、合法状态、正常依赖响应。
- Base：空集合、缺省值、零值、最小分页、无可选能力。
- Bad：非法输入、冲突状态、权限拒绝、依赖失败、超时、取消和重复请求。

高风险代码追加并发竞争、部分成功、恢复、补偿、重放和资源耗尽场景。

## 7. Fixture 与测试数据

- fixture 最小且可读，只包含场景需要的字段。
- builder 提供安全默认值，测试显式覆盖影响行为的字段。
- expected 使用手工确认的 literal/fixture，不复用被测转换器或查询构造器。
- 不复制生产密钥、真实个人数据、线上域名或完整生产载荷。
- 时间、UUID、雪花 ID 和随机值使用固定 fake 或注入源，避免脆弱断言。

## 8. Fake、Mock 与接口

- 优先真实对象，其次简单 fake，最后才是 mock。
- 只 mock 慢或外部边界；不要 mock 被测对象内部实现。
- mock 必须镜像完整合同结构，不能只填当前断言读取的字段。
- 不为测试在生产类型上增加无业务用途的方法。
- 当 mock setup 超过测试行为本身时，改用真实组件集成测试。

## 9. 数据与事务测试

- repository unit test 验证领域意图和错误映射；SQL/ORM 行为由 integration test 验证。
- 覆盖 not-found、唯一冲突、并发更新、分页稳定性、事务回滚和上下文取消。
- 涉及租户、权限、软删除或审计时，必须验证隔离与默认过滤，但不要假设所有项目天然具备这些能力。
- migration 测试覆盖空库升级、已有数据兼容和失败恢复；不得在普通 unit 测试应用生产迁移。

## 10. HTTP 与外部依赖

- handler 测试覆盖解析、校验、认证上下文、错误映射和响应合同。
- 外部 client 测试使用本地 fake server，覆盖状态码、畸形响应、超时和取消。
- 重试测试必须断言可重试条件、次数上界和不可重试错误立即返回。
- 日志、指标和 trace 只在其本身属于验收合同时断言。

## 11. 并发与资源生命周期

- 适用时运行 `go test -race`，但 race 通过不替代并发语义测试。
- goroutine 测试必须有 timeout 和确定性退出，不用任意 sleep 代替同步。
- 覆盖 context 取消、channel 关闭、重复 close、worker 停止和资源释放。
- 测试失败后不得遗留端口、进程、临时文件、数据库或全局环境污染。

## 12. 命名、位置与可维护性

- 测试名描述行为和失败分支，例如 `TestCreateRejectsDuplicateExternalID`。
- package 内部测试与源码同目录；黑盒合同可使用 `_test` package。
- 跨 adapter 集成测试放在 `test/integration`，并使用 build tag。
- 公共测试 helper 只放测试代码，调用者仍能看出场景关键输入。
- 不断言无关日志文本、私有函数、文件行数或实现顺序。

## 13. 完成门槛

- 新行为、修复的 bug 和失败路径都有对应测试。
- 相关测试与全量 unit 通过，format/lint/build 通过。
- 外部条件阻塞的门禁明确记录命令、错误和未验证范围。
- 无跳过测试、快照更新、coverage 下降或 flaky 重试被无说明带入。
- 代码、测试、模块文档和任务验收保持一致。
