<!-- Generated by LoopForge onboarding v2; managed -->
# Dev Task 执行规范

## 唯一状态写入者

`data/tasks/<task-id>.json` 是活跃任务账本，终态文件归档到 `data/tasks/history/YYYY/MM/<task-id>.json`。任务运行期间只有 LoopForge 调度器可以创建、更新、归档并 Git 发布这些文件；项目内 Agent 和脚本一律只读。

- 每次持久状态变化都校验 `expected_version`，提交精确任务路径并 push 到 `origin/main`。
- feature revision 必须先 push，随后 `main` 上的任务 JSON 才能引用该 SHA。
- `completed`、`abandoned` 历史文件不可修改；重新开展必须创建带 `supersedes` 的新任务。
- 活跃任务固定按 `priority`、`created_at`、`id` 排序，不提供手工 reorder。

## 文档引用与回填

- `docs` 是可扩展对象；`module`、`requirements`、`design`、`specs` 是推荐字段，不是封闭 Schema。
- 所有文档路径必须留在对应仓库内；禁止 `..`、绝对路径或符号链接逃逸。
- 推荐长期文档布局是 `docs/<module>/requirements.md`、`design.md`、`specs.md`，已有项目可引用其他 `docs/*` 结构。
- 运行中发现的新稳定事实可以回填项目文档，并在最终 `ready_for_review` 与代码 diff 一并审核。
- 只有新信息使当前任务合同无法继续满足时，Worker 才返回 `contract_change_required`；一般实现选择记录假设后继续。

## 规划系统

- Trellis、OpenSpec 或其他规划系统自行决定目录和工件；执行器只消费适配器返回的状态与引用。
- 没有外部规划系统时，内建规划使用 `.loopforge/task/<item-id>/`。
- 复杂任务进入 `ready_for_review` 前必须通过当前 planning provider 的完整性门禁。

## 分支、Worktree 与 Target

- 用户批准生成文档后，调度器立即预留稳定 task ID、feature branch 与 worktree；后续文档和代码都只能在该位置工作。
- 新任务不得预填分支。单仓默认使用 `loopforge/<project-id>/<task-id>`，显式 Target 使用 `loopforge/<parent-project-id>/<task-id>/<target-id>`。
- 历史分支只有 ownership marker 完全匹配时才能恢复；同名人工分支必须阻塞。
- 显式 `targets[]` 必须解析到已登记仓库；`scope` 定义职责，`after` 定义执行顺序，未知映射不得回退父仓。
- Worker 只向运行结果文件提交 summary、branch、worktree、验证命令和文档回填信息，不直接推进人工状态。

## 状态边界

- Worker 最多建议 `ready_for_review`、`spec_blocked`、`dev_blocked` 或继续 `coding`。
- `accepted` 仅由人工验收产生；`merged`、`completed` 由调度器合入和清理产生；`abandoned` 由人工明确放弃。
- 文档、代码、测试与 Target 完整性在最终 review 一次审核，不增加重复人工门禁。
