#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed
set -euo pipefail
PROJECT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$PROJECT_ROOT_DIR/scripts/java-env.sh"
source "$PROJECT_ROOT_DIR/scripts/build-tool.sh"
cd "$PROJECT_ROOT_DIR"
if [ "$PROJECT_JAVA_BUILD_TOOL" = maven ]; then run_java_build "$PROJECT_ROOT_DIR" -DskipTests package; else run_java_build "$PROJECT_ROOT_DIR" build -x test; fi
