#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed

PROJECT_JAVA_BUILD_TOOL="{{JAVA_BUILD_TOOL}}"

run_java_build() {
  local project_root_dir="$1"
  shift
  case "$PROJECT_JAVA_BUILD_TOOL" in
    maven)
      if [ -x "$project_root_dir/mvnw" ]; then "$project_root_dir/mvnw" "$@"; else mvn "$@"; fi
      ;;
    gradle)
      if [ -x "$project_root_dir/gradlew" ]; then "$project_root_dir/gradlew" "$@"; else gradle "$@"; fi
      ;;
    *) echo '无法确定 Maven 或 Gradle 构建工具。' >&2; return 2 ;;
  esac
}
