#!/usr/bin/env bash
# Generated by LoopForge onboarding v2; managed

if ! command -v java >/dev/null 2>&1; then
  echo '未找到 java，请安装项目要求的 JDK。' >&2
  return 1 2>/dev/null || exit 1
fi
if [ -n "${JAVA_HOME:-}" ] && [ ! -x "${JAVA_HOME}/bin/java" ]; then
  echo "忽略无效 JAVA_HOME：${JAVA_HOME}" >&2
  unset JAVA_HOME
fi
